### ISSUE TITLE
Ensemble models

### ISSUE THREAD

**Issue by jaimedantas** [EECS-4404/ensemble#1]
The three models need to be combined to create a weighted average ensemble.

**Basic documentation:** 
[Ensemble](https://machinelearningmastery.com/ensemble-methods-for-deep-learning-neural-networks/)

[Weighted average ensemble](
https://machinelearningmastery.com/weighted-average-ensemble-for-deep-learning-neural-networks/)

**Comment by nizwakhan** [comment]
Done with weighted ensemble learning. 
Optimal Weights = [0.25(predictor 1),0.25(predictor 2),0.5(predictor 3)]
Accuracy achieved using optimal weights  =  0.9665 and F1 score = 0.9556585043017869  which is slightly higher than predictor 3 which reported the best performance ( accuracy = 0.963 and F1 score = 0.9506008010680908 )
